### ISSUE TITLE
Undefined encounters variable

### ISSUE THREAD

**Issue by trostalski** [gernotpuc/case-study-ml-acute-leukemia#2]
The variable seems to be undefined here https://github.com/gernotpuc/case-study-ml-acute-leukemia/blob/f8956228d7154c957db1bf713b9bb4a02d87a389/cohort-extraction-fhir/cohort_ume_aipal.ipynb#L159

**Comment by trostalski** [comment]
![image](https://github.com/gernotpuc/case-study-ml-acute-leukemia/assets/48415966/76956b30-8ab7-4403-8076-6f2db49d0332)

**Comment by trostalski** [comment]
maybe:

```python
encounters = conditions_df_dis['encounter_reference'].dropna().drop_duplicates().reset_index(drop=True).str.split('Encounter/').str[-1]
encounters = pd.DataFrame(encounters, columns=['encounter_reference'])
```

**Comment by gernotpuc** [comment]
Error was fixed by creating a new variable encounters and adding the dataframe conversion.

`encounters = conditions_df_dis['encounter_reference'].dropna().drop_duplicates().reset_index(drop=True).str.split('Encounter/').str[-1].to_frame(name='encounter_reference')
`
